name = "meetings"
main = "src/index.js"
compatibility_date = "2024-03-01"

# Non-sensitive public configurations only
[vars]
OPENROUTER_MODEL = "openrouter/free"

[[d1_databases]]
binding = "meet"
database_name = "meet"
database_id = "0a628465-af52-4c5b-adaa-fddf66178351"
